name: "Pull Request Labeler"
on: [pull_request]

jobs:
  add-topic-area-labels:
    name: Add topic and area labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
  add-kind-labels:
    name: Add kind labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(context)
            const { default: addLabelsToPR } = await import('${{ github.workspace }}/.github/scripts/add-labels.js') ;
            await addLabelsToPR({github, context})
